2018-11-29 22:18:56,697  kannan gen_consumer::<module>()  INFO  (PID: 32754)>  Validator started to Execute at 1543510136.7
2018-11-29 22:18:56,697  kannan gen_consumer::<module>()  INFO  (PID: 32754)>  reading configs required for validator consumer from file consumer_config.yml in utils dir
2018-11-29 22:18:56,704  kannan gen_consumer::<module>()  INFO  (PID: 32754)>  Starting to consume
2018-11-29 22:18:56,715  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,716  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,716  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,717  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,717  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,718  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,718  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,721  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,723  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,723  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,724  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,724  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,725  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,725  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,729  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,729  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,730  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,730  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,731  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,731  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,732  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,735  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,736  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,737  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,737  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,738  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,738  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,739  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,744  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,745  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,746  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,746  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,747  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,747  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,748  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,755  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,757  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,757  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,758  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,759  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,760  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,761  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,771  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,775  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,776  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,777  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,777  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,779  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,779  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,786  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,788  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,789  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,789  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,790  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,791  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,793  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,798  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,800  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,801  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,802  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,803  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,805  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,806  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,812  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,813  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,813  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,814  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,814  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,817  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,818  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,822  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,823  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,823  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,824  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,825  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,826  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,826  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,831  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,831  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,833  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,834  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,834  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,835  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,836  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,840  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,842  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,842  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,843  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,843  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,844  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,845  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,849  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,850  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,851  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,851  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,852  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,853  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,853  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,858  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,859  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,859  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,860  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,860  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,861  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,862  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,868  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,869  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,870  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,870  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,871  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,872  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,872  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,878  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,879  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,880  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,880  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,882  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,884  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,885  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,889  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,890  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,891  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,891  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,892  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,893  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,893  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,898  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,900  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,901  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,902  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,902  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,903  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,904  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,909  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,910  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,910  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,911  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,912  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,915  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,916  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,923  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,923  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,924  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,924  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,925  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,926  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,927  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,936  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,937  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,938  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,938  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,939  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,940  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,941  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,952  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,952  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,953  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,953  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,954  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,955  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,955  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,960  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,961  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,961  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,961  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,962  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,963  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,964  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
2018-11-29 22:18:56,970  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,971  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,972  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'} of  type gen_summary is being processed to store in gen_summary
2018-11-29 22:18:56,972  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,972  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,974  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,974  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'12346', 'type': u'gen_summary', 'ticket_num': u'srno123'}, 'payload': {u'details': [{u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}, {u'source': u'10.10.10.3', u'destination': u'10.172.2.3', u'protocol': u'tcp', u'port': 22, u'input-row-id': 2}, {u'source': u'10.10.10.1', u'destination': u'10.172.2.1', u'protocol': u'tcp', u'port': 22, u'input-row-id': 1}], u'summary': {u'red_flags': 5, u'recomm_for': 15, u'total_recs': 30, u'existing': 10}}}
2018-11-29 22:18:56,979  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,979  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,980  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'} of  type existing_policies is being processed to store in generate
2018-11-29 22:18:56,980  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,981  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,983  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,984  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'existing_policies', 'ticket_num': u'srno123'}, 'payload': {u'Existing_Policies': [{u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180622-001260_Abhimanyu_247', u'Source-IP': u'10.197.16.181', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2357}, {u'Firewall': u'am2-fa-c2r304-fw-3', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180626-002921_pvkondap_1', u'Source-IP': u'10.197.18.118', u'Destination-IP': u'92.246.34.177', u'Port': u'22', u'Input-Row-ID': 2359}, {u'Firewall': u'am2-opc-fw-1', u'Policy-Name': u'PRIVATE-MT:UNTRUST:180614-001017_oupadhya_263', u'Source-IP': u'10.111.217.216', u'Destination-IP': u'92.60.244.8', u'Port': u'22', u'Input-Row-ID': 2361}]}}
2018-11-29 22:18:56,988  kannan gen_consumer::process()  INFO  (PID: 32754)>  strting datastore process for
2018-11-29 22:18:56,989  kannan gen_consumer::process()  INFO  (PID: 32754)>  Message verification passed
2018-11-29 22:18:56,990  kannan gen_consumer::process()  INFO  (PID: 32754)>  msg {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'} of  type red_flags is being processed to store in generate
2018-11-29 22:18:56,990  kannan data_store_driver::store()  INFO  (PID: 32754)>  Message verification succesfull
2018-11-29 22:18:56,991  kannan data_store::inner()  INFO  (PID: 32754)>  Connecting to db
2018-11-29 22:18:56,992  kannan data_store_driver::store()  ERROR  (PID: 32754)>  Message already exist in the table
2018-11-29 22:18:56,993  kannan gen_consumer::process()  ERROR  (PID: 32754)>  {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
Traceback (most recent call last):
  File "gen_consumer.py", line 93, in process
    raise MsgDataStoreFailed(self.new_msg)
MsgDataStoreFailed: {'header': {'username': u'kannan', 'correlation_id': u'11111', 'type': u'red_flags', 'ticket_num': u'srno123'}, 'payload': {u'Red_flags': [{u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.92.218', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 795}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.96.64', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 796}, {u'Routing-Issue-Reason': u'FRF-1005', u'Destination-Firewall': u'ch3-opc-fw-1', u'Source-IP': u'10.54.94.8', u'Dest-Zone-2': u'PUBLIC-FT', u'Source-Zone': u'PRIVATE-MT', u'Dest-Zone': u'UNTRUST', u'Destination-IP': u'160.34.0.20', u'Source-Zone-2': u'TRUST', u'Source-Firewall': u'iad37-fa-c5r101-fw-2', u'Port': u'22', u'Input-Row-ID': 797}]}}
connection closed
keyboard interrupt
2018-11-29 22:18:57,012  kannan gen_consumer::<module>()  ERROR  (PID: 32754)>  KeyboardInterrupt
Traceback (most recent call last):
  File "gen_consumer.py", line 145, in <module>
    conn.consume(callback)
  File "/home/navi/Desktop/changemanager/lib/consumer.py", line 37, in consume
    self.channel.start_consuming ()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1822, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 758, in process_data_events
    self._dispatch_channel_events()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 521, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1445, in _dispatch_events
    evt.body)
  File "/home/navi/Desktop/changemanager/lib/consumer.py", line 78, in _consume_message
    self.channel.basic_nack (delivery_tag=method.delivery_tag,requeue=True)
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2054, in basic_nack
    self._flush_output()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_output
    self._impl.ioloop.poll()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/home/navi/.local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 465, in _handle_read
    return len(data)
KeyboardInterrupt
